CREATE INDEX "journals_user_id_idx" ON "journals"("user_id");
CREATE INDEX "habits_user_id_idx" ON "habits"("user_id");
CREATE INDEX "morningPages_user_id_idx" ON "morningPages"("user_id");
CREATE INDEX "morningPages_journal_id_idx" ON "morningPages"("journal_id");
CREATE INDEX "eveningPages_user_id_idx" ON "eveningPages"("user_id");
CREATE INDEX "eveningPages_journal_id_idx" ON "eveningPages"("journal_id");
CREATE INDEX "projects_user_id_idx" ON "projects"("user_id");
CREATE INDEX "FETUS_projectID_createdAt_idx" ON "FETUS"("projectID", "createdAt" DESC);
CREATE INDEX "goals_currentProjectID_status_idx" ON "goals"("currentProjectID", "status");
CREATE INDEX "goals_currentProjectID_priority_idx" ON "goals"("currentProjectID", "priority");
CREATE INDEX "tasks_goal_id_idx" ON "tasks"("goal_id");
CREATE INDEX "tasks_project_id_idx" ON "tasks"("project_id");
CREATE INDEX "subTasks_goal_id_idx" ON "subTasks"("goal_id");
CREATE INDEX "subTasks_task_id_idx" ON "subTasks"("task_id");
CREATE INDEX "subTasks_project_id_idx" ON "subTasks"("project_id");
CREATE INDEX "weekInReviewPages_user_id_idx" ON "weekInReviewPages"("user_id");
CREATE INDEX "weekInReviewPages_journal_id_idx" ON "weekInReviewPages"("journal_id");
CREATE INDEX "planningNextWeekPages_user_id_idx" ON "planningNextWeekPages"("user_id");
CREATE INDEX "planningNextWeekPages_journal_id_idx" ON "planningNextWeekPages"("journal_id");
CREATE INDEX "freedays_user_id_idx" ON "freedays"("user_id");
CREATE INDEX "freedays_journal_id_idx" ON "freedays"("journal_id");